basePath: /
definitions:
  handlers.CreateReferralCodeInput:
    properties:
      expiry:
        type: string
    type: object
  handlers.RegisterWithReferralCodeInput:
    properties:
      email:
        type: string
      password:
        type: string
      referral_code:
        type: string
    type: object
  handlers.User:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для системы реферальных ссылок
  title: Referral System API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Auth of user
      parameters:
      - description: User data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: User's login
      tags:
      - Users
  /auth/register:
    post:
      consumes:
      - application/json
      description: Registration of new user
      parameters:
      - description: User registration data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Registration
      tags:
      - Users
  /referral/create:
    post:
      consumes:
      - application/json
      description: Create a new referral code for the authenticated user
      parameters:
      - description: Expiry time for the referral code
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateReferralCodeInput'
      produces:
      - application/json
      responses:
        "200":
          description: referral_code
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Create a referral code
      tags:
      - Referrals
  /referral/delete:
    delete:
      description: Delete the referral code for the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: message
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Delete a referral code
      tags:
      - Referrals
  /referral/get/{email}:
    get:
      description: Get the referral code for a user by their email
      parameters:
      - description: User email
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: referral_code
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get referral code by email
      tags:
      - Referrals
  /referral/register:
    post:
      consumes:
      - application/json
      description: Register a new user with a referral code
      parameters:
      - description: User registration data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.RegisterWithReferralCodeInput'
      produces:
      - application/json
      responses:
        "200":
          description: message
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user with a referral code
      tags:
      - Referrals
  /referrals/referrer/{id}:
    get:
      description: Get the list of users referred by a specific referrer
      parameters:
      - description: Referrer ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: emails
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get referrals by referrer ID
      tags:
      - Referrals
swagger: "2.0"
